---
title: "Microbiota"
subtitle: "Lesson 3"
author: "Marco Chiapello"
date: "???"
output:
  xaringan::moon_reader:
    css: ["scrollable.css", "mtheme_max.css", "fonts_mtheme_max.css", "lesson3.css"]
    self_contained: false
    lib_dir: libs
    chakra: libs/remark-latest.min.js
    nature:
      ratio: '16:9'
      highlightStyle: github
      highlightLines: true
    countIncrementalSlides: false
    seal: false  
---

```{r setup, include=FALSE, cache=FALSE}
# TO render: rmarkdown::render('Lesson3.Rmd', 'xaringan::moon_reader')

# set working directory to docs folder
setwd(here::here())

# Set global R options
options(htmltools.dir.version = FALSE, servr.daemon = TRUE)

# Set global knitr chunk options
knitr::opts_chunk$set(
  fig.align = "center", 
  cache = TRUE,
  error = FALSE,
  message = FALSE, 
  warning = FALSE, 
  collapse = TRUE 
)

# This is good for getting the ggplot background consistent with
# the html background color
# library(ggplot2)
# thm <- theme_bw()
# theme_set(thm)

# library(RefManageR)
# BibOptions(check.entries = FALSE,
#            bib.style = "authoryear",
#            cite.style = "authoryear",
#            style = "markdown",
#            hyperlink = FALSE,
#            max.names = 2,
#            dashed = FALSE)
# bib <- ReadBib("biblio/bib.bib", check = FALSE)
```

```{r xaringanExtra, echo=FALSE}
library(xaringanExtra)
use_tile_view() 
#use_scribble()
use_animate_css()
#use_logo(image_url = "images/IPSPweb_ITA.jpg")
#use_search(show_icon = TRUE)
```

class: title-slide


# .font120[.center[Fungal interactions]]
# .font100[.center[from bioremediation to biocontrol agents]] 
# .font100[.center[through mycorrhizal symbiosis]]


<br><br>
.marco[
.tada[Marco Chiapello]
<br>
2021-03-29
]

.rigth[Seminario - Istituto per la Protezione Sostenibile delle Piante]

???

.parR[
Buongiorno a tutti
]